kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  labels:
    backstage.io/kubernetes-id: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
