kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    backstage.io/kubernetes-id: minio
spec:
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: minio
