apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: 3scale
spec:
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: 3scale
  wildcardDomain: $ROUTER_BASE
