apiVersion: batch/v1
kind: CronJob
metadata:
  name: say-hello
  labels:
    backstage.io/kubernetes-id: developer-hub
    app.kubernetes.io/part-of: rhdh-start-scripts
spec:
  # Run Daily
  schedule: '0 0 * * *' # Daily instead of hourly
  jobTemplate:
    metadata:
      labels:
        backstage.io/kubernetes-id: developer-hub
    spec:
      template:
        metadata:
          labels:
            backstage.io/kubernetes-id: developer-hub
        spec:
          containers:
            - name: hello
              image: internal-busy-box:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              resources:
                requests:
                  cpu: 5m
                  memory: 10Mi
                limits:
                  cpu: 10m
                  memory: 20Mi
          restartPolicy: OnFailure
