apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemonset
  labels:
    backstage.io/kubernetes-id: developer-hub
    app.kubernetes.io/part-of: rhdh-start-scripts

spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: developer-hub
        app: test
    spec:
      containers:
        - name: test-container
          image: internal-busy-box:latest
          imagePullPolicy: IfNotPresent
          # Print test 57 times, with each print coming once every 5 seconds
          command:
            [
              'sh',
              '-c',
              "for i in $(seq 1 10); do echo 'Iteration:' $i && date; sleep 6; done",
            ]
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 20Mi
