apiVersion: batch/v1
kind: Job
metadata:
  name: print-pi
  labels:
    backstage.io/kubernetes-id: developer-hub
    app.kubernetes.io/part-of: rhdh-start-scripts
spec:
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: developer-hub
    spec:
      containers:
        - name: pi
          image: internal-perl:5.34.0
          imagePullPolicy: IfNotPresent
          # Print out the first 128 digits of PI
          command: ['perl', '-Mbignum=bpi', '-wle', 'print bpi(128)']
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Never
  backoffLimit: 4
