apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-statefulset
  labels:
    backstage.io/kubernetes-id: developer-hub
    app.kubernetes.io/part-of: rhdh-start-scripts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  serviceName: example-service
  template:
    metadata:
      labels:
        app: example-app
        backstage.io/kubernetes-id: developer-hub
    spec:
      containers:
        - name: example-container
          image: internal-nginxdemos-hello:plain-text
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    backstage.io/kubernetes-id: developer-hub
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
