kind: ConfigMap
apiVersion: v1
metadata:
  name: operators-config-map
  labels:
    backstage.io/kubernetes-id: developer-hub
data:
  operators.yaml: |
    # RHSSO and Keycloak
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: rhsso-operator
      title: Red Hat Single Sign-On Operator
      description: Operator that is used to configure Red Hat Single Sign-On through the use of Keycloak for an OpenShift instance
      annotations:
        backstage.io/kubernetes-id: rhsso-operator
        backstage.io/kubernetes-namespace: rhdh
    spec:
      type: operator
      owner: cluster-admins
      dependencyOf: component:default/backstage-community-keycloak
      dependsOn: 
        - resource:default/test-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: keycloak
      title: Keycloak
      description: Red Hat Single Sign-On Operator deployment of Keycloak
      annotations:
        backstage.io/kubernetes-id: keycloak
        backstage.io/kubernetes-namespace: rhdh
      links:
        - url: https://www.keycloak.org/documentation
          title: Documentation
          icon: web
    spec:
      type: identity-provider
      lifecycle: production
      owner: cluster-admins
      dependencyOf: component:default/backstage-community-keycloak
      dependsOn: 
        - resource:default/rhsso-operator
    ---
    # ACM, Multiclusterhub, search
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: acm-operator
      title: Advanced Cluster Manager for Kubernetes Operator
      description: Operator that is used to configure the Advanced Cluster Manager for an OpenShift instance
      annotations:
        backstage.io/kubernetes-id: acm-operator
        backstage.io/kubernetes-namespace: rhdh
    spec:
      type: operator
      owner: cluster-admins
      dependencyOf: component:default/backstage-community-ocm
      dependsOn: 
        - resource:default/test-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: search-operator
      title: Search Operator
      description: Operator that is used in conjuction with the Advanced Cluster Manager for an OpenShift instance
      annotations:
        backstage.io/kubernetes-id: search-operator
        backstage.io/kubernetes-namespace: rhdh
    spec:
      type: operator
      owner: cluster-admins
      dependencyOf: component:default/backstage-community-ocm
      dependsOn: 
        - resource:default/test-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: multiclusterhub
      title: MultiClusterHub
      description: Advanced Cluster Manager deployment of the MultiClusterHub
      annotations:
        backstage.io/kubernetes-id: multiclusterhub
        backstage.io/kubernetes-namespace: rhdh
    spec:
      type: operator
      owner: cluster-admins
      dependencyOf: component:default/backstage-community-ocm
      dependsOn: 
        - resource:default/acm-operator
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: pipelines-operator
      title: Red Hat OpenShift Pipelines Operator
      description: Operator that is used to configure Red Hat OpenShift Pipelines for an OpenShift instance
      annotations:
        backstage.io/kubernetes-id: pipelines-operator
        backstage.io/kubernetes-namespace: openshift-operators
    spec:
      type: operator
      owner: cluster-admins
      dependencyOf: component:default/backstage-plugin-tekton-workspace
      dependsOn: 
        - resource:default/test-cluster
