#!/bin/bash

# =============================================================================
# Nexus Repository Manager Plugin Configuration
# =============================================================================
# This script deploys and configures resources required for the Nexus
# Repository Manager plugin integration with RHDH.
# =============================================================================

deploy_nexus() {
  echo "Deploying Nexus Repository Manager Operator..."
  oc apply -f $PWD/resources/operators/nexus-subscription.yaml --namespace=${NAMESPACE}
}

deploy_nexus_resources() {
  # Wait for operator to be ready
  echo "Waiting for Nexus operator to become ready..."
  SECONDS=0
  while true; do
    STATUS=$(oc get csv --namespace=${NAMESPACE} 2>/dev/null | grep nxrm-operator | awk '{print $NF}')

    if [[ "$STATUS" == "Succeeded" ]]; then
      echo "Nexus operator is ready!"
      break
    fi

    if [[ $SECONDS -ge $TIMEOUT ]]; then
      echo "Timeout waiting for Nexus operator to become ready."
      exit 1
    fi

    echo "Nexus operator not ready yet. Retrying in $INTERVAL seconds..."
    sleep "$INTERVAL"
  done

  # Deploy Nexus Repository Manager instance
  echo "Deploying Nexus Repository Manager instance..."
  oc apply -f $PWD/resources/nexus/nexus-repo.yaml --namespace=${NAMESPACE}

  # Wait for Nexus instance to be ready
  echo "Waiting for Nexus instance to be ready..."
  SECONDS=0
  while true; do
    NEXUS_STATUS=$(oc get nexusrepo nexus-repo --namespace=${NAMESPACE} -o jsonpath='{.status.nexusStatus}' 2>/dev/null)

    if [[ "$NEXUS_STATUS" == "Running" ]] || [[ "$NEXUS_STATUS" == "Ready" ]]; then
      echo "Nexus instance is ready!"
      break
    fi

    if [[ $SECONDS -ge $TIMEOUT ]]; then
      echo "Timeout waiting for Nexus instance to become ready."
      echo "Current status: ${NEXUS_STATUS}"
      exit 1
    fi

    echo "Nexus instance not ready yet (status: ${NEXUS_STATUS}). Retrying in $INTERVAL seconds..."
    sleep "$INTERVAL"
  done
}

config_secrets_for_nexus_plugins() {
  echo "Configuring secrets for Nexus plugin..."

  # Get Nexus URL from the route
  NEXUS_URL=$(oc get route nexus-repo --namespace=${NAMESPACE} -o jsonpath='{.spec.host}' 2>/dev/null)
  
  if [[ -z "$NEXUS_URL" ]]; then
    echo "Warning: Could not retrieve Nexus URL from route. Checking service..."
    NEXUS_URL="nexus-repo-service.${NAMESPACE}.svc.cluster.local:8081"
  fi

  # Get admin credentials from secret (generated by operator)
  NEXUS_PASSWORD=$(oc get secret nexus-admin-credentials --namespace=${NAMESPACE} -o jsonpath='{.data.password}' 2>/dev/null | base64 -d)
  
  if [ -z "$NEXUS_PASSWORD" ]; then
    echo "Error: Nexus admin credentials not found"
    echo "The nexus-admin-credentials secret must exist before running this job"
    echo "This is typically created by the Nexus operator during installation"
    exit 1
  fi

  NEXUS_USERNAME="admin"

  # Generate Base64-encoded auth header for proxy (frontend plugin requirement)
  NEXUS_AUTH_HEADER=$(echo -n "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" | base64 -w 0)

  # Ensure local secrets file exists
  if [ ! -f "$PWD/resources/user-resources/rhdh-secrets.local.yaml" ]; then
    echo "Creating local secrets file..."
    cp $PWD/resources/rhdh/rhdh-secrets.yaml $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  # Update secrets file with Nexus configuration
  echo "Updating RHDH secrets with Nexus configuration..."
  
  # Add or update NEXUS_URL (include https://)
  if grep -q "NEXUS_URL:" $PWD/resources/user-resources/rhdh-secrets.local.yaml; then
    sed -i "s|NEXUS_URL:.*|NEXUS_URL: $(echo -n "https://$NEXUS_URL" | base64 -w 0)|g" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  else
    sed -i "/^data:/a\\  NEXUS_URL: $(echo -n "https://$NEXUS_URL" | base64 -w 0)" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  # Add or update NEXUS_AUTH_HEADER (for proxy authentication)
  if grep -q "NEXUS_AUTH_HEADER:" $PWD/resources/user-resources/rhdh-secrets.local.yaml; then
    sed -i "s|NEXUS_AUTH_HEADER:.*|NEXUS_AUTH_HEADER: $(echo -n "$NEXUS_AUTH_HEADER" | base64 -w 0)|g" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  else
    sed -i "/^data:/a\\  NEXUS_AUTH_HEADER: $(echo -n "$NEXUS_AUTH_HEADER" | base64 -w 0)" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  echo "Nexus configuration completed:"
  echo "  URL: https://$NEXUS_URL"
  echo "  Username: $NEXUS_USERNAME"
  echo "  Auth Header: [configured in secrets]"
  echo ""
  echo "NOTE: This plugin uses a frontend proxy configuration."
  echo "You must add the proxy configuration to your dynamic-plugins-configmap.yaml."
  echo "See docs/nexus.md for the required proxy configuration."
}

apply_nexus_labels() {
  echo "Applying Kubernetes labels for Nexus resources..."
  
  # Define label patterns for Nexus resources
  declare -A patterns=(
    ["nexus"]="backstage.io/kubernetes-id=nexus-repo"
    ["nxrm-operator"]="backstage.io/kubernetes-id=nxrm-operator"
  )

  resource_types=("pods" "deployments" "replicasets" "services" "routes" "statefulsets")

  for resource in "${resource_types[@]}"; do
    for pattern in "${!patterns[@]}"; do
      label="${patterns[$pattern]}"
      oc get "$resource" -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" 2>/dev/null \
        | grep "$pattern" \
        | xargs -I {} oc label "$resource" {} "$label" --overwrite -n $NAMESPACE 2>/dev/null || true
    done
  done
  
  echo "Labels applied successfully!"
}

populate_nexus_demo_data() {
  # Check if demo data population is enabled
  if [[ "${POPULATE_DEMO_DATA:-true}" == "false" ]]; then
    echo "Demo data population disabled, skipping..."
    return 0
  fi

  echo "Populating Nexus with demo data..."

  # Deploy the demo data job
  oc apply -f $PWD/resources/nexus/populate-demo-data-job.yaml --namespace=${NAMESPACE}

  # Wait for job to complete
  echo "Waiting for demo data population job to complete..."
  oc wait --for=condition=complete --timeout=600s \
    job/nexus-populate-demo-data -n ${NAMESPACE} 2>/dev/null || {
      echo "Warning: Demo data population job did not complete successfully."
      echo "Check job logs with: oc logs -n ${NAMESPACE} job/nexus-populate-demo-data"
      # Don't fail the entire setup if demo data fails
      return 0
    }

  echo "Demo data population completed!"
}

register_nexus_demo_catalog_entities() {
  # Check if demo data population is enabled
  if [[ "${POPULATE_DEMO_DATA:-true}" == "false" ]]; then
    echo "Demo data disabled, skipping catalog entity registration..."
    return 0
  fi

  echo "Registering Nexus demo catalog entities..."

  # Create ConfigMap for demo catalog entities
  oc create configmap nexus-demo-entities-config-map \
    --from-file=demo-nexus-artifacts.yaml=$PWD/resources/nexus/demo-catalog-entities.yaml \
    --namespace=${NAMESPACE} \
    --dry-run=client -o yaml | oc apply -f - --namespace=${NAMESPACE}

  # Add label for Backstage to discover
  oc label configmap nexus-demo-entities-config-map \
    backstage.io/kubernetes-id=developer-hub \
    --overwrite -n ${NAMESPACE}

  echo "Demo catalog entities registered!"
  echo "Entities will be available in RHDH catalog:"
  echo "  - Component: hello-world-lib (Maven)"
  echo "  - Component: hello-world-npm (npm)"
  echo "  - System: demo-system"
  echo "  - Group: platform-team"
}

uninstall_nexus() {
  echo "Uninstalling Nexus Repository Manager..."

  # Delete demo catalog entities ConfigMap
  oc delete configmap nexus-demo-entities-config-map --namespace=${NAMESPACE} 2>/dev/null || true

  # Delete demo data job
  oc delete job nexus-populate-demo-data --namespace=${NAMESPACE} 2>/dev/null || true

  # Delete Nexus instance
  oc delete nexusrepo nexus-repo --namespace=${NAMESPACE} 2>/dev/null || true

  # Wait for resources to be cleaned up
  sleep 10

  # Uninstall the operator
  OPERATOR=$(oc get csv --namespace=${NAMESPACE} 2>/dev/null | grep nxrm-operator | awk '{print $1}')
  if [[ -n "$OPERATOR" ]]; then
    oc delete clusterserviceversion $OPERATOR --namespace=${NAMESPACE}
  fi
  oc delete subscription nexus-operator-subscription --namespace=${NAMESPACE} 2>/dev/null || true

  echo "Nexus Repository Manager uninstalled!"
}

main() {
  source "${PWD}/env_variables.sh"
  source "${PWD}/.env"

  echo "=============================================="
  echo "Configuring Nexus Repository Manager Plugin"
  echo "=============================================="

  deploy_nexus
  deploy_nexus_resources
  config_secrets_for_nexus_plugins
  apply_nexus_labels
  populate_nexus_demo_data
  register_nexus_demo_catalog_entities

  echo ""
  echo "=============================================="
  echo "Nexus Repository Manager configuration complete!"
  echo "=============================================="

  exit "${OVERALL_RESULT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
