#!/bin/bash

# =============================================================================
# ArgoCD Plugin Configuration
# =============================================================================
# This script deploys and configures resources required for the ArgoCD
# plugin integration with RHDH.
#
# Supported Plugins:
# - @roadiehq/backstage-plugin-argo-cd (frontend)
# - @roadiehq/backstage-plugin-argo-cd-backend (backend)
# - @backstage-community/plugin-argocd (frontend)
# - @backstage-community/plugin-argocd-backend (backend)
#
# NOTE: Users should enable both plugins from the same repository:
#   - Enable BOTH RoadieHQ plugins OR
#   - Enable BOTH Backstage Community plugins
#   - DO NOT mix plugins from different repositories
# =============================================================================

deploy_argocd() {
  echo "Deploying ArgoCD Operator..."
  oc apply -f $PWD/resources/operators/argocd-subscription.yaml
}

wait_for_argocd_operator_and_deploy_instance() {
  # Wait for operator to be ready
  echo "Waiting for ArgoCD operator to become ready..."
  SECONDS=0
  while true; do
    STATUS=$(oc get csv --namespace="openshift-operators" 2>/dev/null | grep argocd-operator | awk '{print $NF}')

    if [[ "$STATUS" == "Succeeded" ]]; then
      echo "ArgoCD operator is ready!"
      break
    fi

    if [[ $SECONDS -ge $TIMEOUT ]]; then
      echo "Timeout waiting for ArgoCD operator to become ready."
      exit 1
    fi

    echo "ArgoCD operator not ready yet. Retrying in $INTERVAL seconds..."
    sleep "$INTERVAL"
  done

  # Deploy ArgoCD instance (immediately after operator is ready)
  echo "Deploying ArgoCD instance..."
  oc apply -f $PWD/resources/argocd/argocd-instance.yaml --namespace=${NAMESPACE}
}

wait_for_argocd_instance_and_deploy_demo_applications() {
  # Wait for ArgoCD instance to be ready
  echo "Waiting for ArgoCD instance to be ready..."
  SECONDS=0
  while true; do
    ARGOCD_STATUS=$(oc get argocd argocd --namespace=${NAMESPACE} -o jsonpath='{.status.phase}' 2>/dev/null)

    if [[ "$ARGOCD_STATUS" == "Available" ]]; then
      echo "ArgoCD instance is ready!"
      break
    fi

    if [[ $SECONDS -ge $TIMEOUT ]]; then
      echo "Timeout waiting for ArgoCD instance to become ready."
      echo "Current status: ${ARGOCD_STATUS}"
      exit 1
    fi

    echo "ArgoCD instance not ready yet (status: ${ARGOCD_STATUS}). Retrying in $INTERVAL seconds..."
    sleep "$INTERVAL"
  done

  # Deploy demo ArgoCD applications (immediately after instance is ready)
  echo "Deploying demo ArgoCD applications..."
  oc apply -f $PWD/resources/argocd/demo-applications.yaml --namespace=${NAMESPACE}
}

config_secrets_for_argocd_plugins() {
  echo "Configuring secrets for ArgoCD plugins..."

  # Get ArgoCD URL from the route
  ARGOCD_URL=$(oc get route argocd-server --namespace=${NAMESPACE} -o jsonpath='{.spec.host}' 2>/dev/null)
  
  if [[ -z "$ARGOCD_URL" ]]; then
    echo "Warning: Could not retrieve ArgoCD URL from route."
    ARGOCD_URL="argocd-server.${NAMESPACE}.svc.cluster.local"
  fi

  # Get admin password from secret (generated by operator)
  ARGOCD_PASSWORD=$(oc get secret argocd-cluster --namespace=${NAMESPACE} -o jsonpath='{.data.admin\.password}' 2>/dev/null | base64 -d)
  
  if [ -z "$ARGOCD_PASSWORD" ]; then
    echo "Warning: ArgoCD admin password not found in argocd-cluster secret"
    echo "Checking argocd-initial-admin-secret..."
    ARGOCD_PASSWORD=$(oc get secret argocd-initial-admin-secret --namespace=${NAMESPACE} -o jsonpath='{.data.password}' 2>/dev/null | base64 -d)
  fi

  if [ -z "$ARGOCD_PASSWORD" ]; then
    echo "Error: ArgoCD admin credentials not found"
    echo "The ArgoCD admin password secret must exist before running this job"
    echo "This is typically created by the ArgoCD operator during installation"
    exit 1
  fi

  ARGOCD_USERNAME="admin"

  # Generate authentication token using ArgoCD API
  echo "Generating ArgoCD authentication token..."
  
  # Use the ArgoCD CLI if available, otherwise use API directly
  if command -v argocd &> /dev/null; then
    ARGOCD_TOKEN=$(argocd account generate-token --account admin --server "$ARGOCD_URL" --insecure 2>/dev/null || echo "")
  fi

  # If token generation failed or argocd CLI not available, use password directly
  if [ -z "$ARGOCD_TOKEN" ]; then
    echo "Using password-based authentication (token generation not available)"
    ARGOCD_TOKEN="$ARGOCD_PASSWORD"
  fi

  # Ensure local secrets file exists
  if [ ! -f "$PWD/resources/user-resources/rhdh-secrets.local.yaml" ]; then
    echo "Creating local secrets file..."
    cp $PWD/resources/rhdh/rhdh-secrets.yaml $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  # Update secrets file with ArgoCD configuration
  echo "Updating RHDH secrets with ArgoCD configuration..."
  
  # Add or update ARGOCD_URL
  if grep -q "ARGOCD_INSTANCE1_URL:" $PWD/resources/user-resources/rhdh-secrets.local.yaml; then
    sed -i "s|ARGOCD_INSTANCE1_URL:.*|ARGOCD_INSTANCE1_URL: $(echo -n "https://$ARGOCD_URL" | base64 -w 0)|g" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  else
    sed -i "/^data:/a\\  ARGOCD_INSTANCE1_URL: $(echo -n "https://$ARGOCD_URL" | base64 -w 0)" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  # Add or update ARGOCD_USERNAME
  if grep -q "ARGOCD_USERNAME:" $PWD/resources/user-resources/rhdh-secrets.local.yaml; then
    sed -i "s|ARGOCD_USERNAME:.*|ARGOCD_USERNAME: $(echo -n "$ARGOCD_USERNAME" | base64 -w 0)|g" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  else
    sed -i "/^data:/a\\  ARGOCD_USERNAME: $(echo -n "$ARGOCD_USERNAME" | base64 -w 0)" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  # Add or update ARGOCD_PASSWORD
  if grep -q "ARGOCD_PASSWORD:" $PWD/resources/user-resources/rhdh-secrets.local.yaml; then
    sed -i "s|ARGOCD_PASSWORD:.*|ARGOCD_PASSWORD: $(echo -n "$ARGOCD_PASSWORD" | base64 -w 0)|g" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  else
    sed -i "/^data:/a\\  ARGOCD_PASSWORD: $(echo -n "$ARGOCD_PASSWORD" | base64 -w 0)" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  # Add or update ARGOCD_AUTH_TOKEN
  if grep -q "ARGOCD_AUTH_TOKEN:" $PWD/resources/user-resources/rhdh-secrets.local.yaml; then
    sed -i "s|ARGOCD_AUTH_TOKEN:.*|ARGOCD_AUTH_TOKEN: $(echo -n "$ARGOCD_TOKEN" | base64 -w 0)|g" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  else
    sed -i "/^data:/a\\  ARGOCD_AUTH_TOKEN: $(echo -n "$ARGOCD_TOKEN" | base64 -w 0)" \
      $PWD/resources/user-resources/rhdh-secrets.local.yaml
  fi

  echo "ArgoCD configuration completed:"
  echo "  URL: https://$ARGOCD_URL"
  echo "  Username: $ARGOCD_USERNAME"
  echo "  Password: [configured in secrets]"
  echo "  Auth Token: [configured in secrets]"
  echo ""
  echo "NOTE: This supports both RoadieHQ and Backstage Community ArgoCD plugins."
  echo "Choose ONE set of plugins (both frontend and backend from same source):"
  echo "  Option 1: @roadiehq/backstage-plugin-argo-cd + @roadiehq/backstage-plugin-argo-cd-backend"
  echo "  Option 2: @backstage-community/plugin-argocd + @backstage-community/plugin-argocd-backend"
}

apply_argocd_labels() {
  echo "Applying Kubernetes labels for ArgoCD resources..."
  
  # Define label patterns for ArgoCD resources
  declare -A patterns=(
    ["argocd-server"]="backstage.io/kubernetes-id=argocd-instance"
    ["argocd-repo-server"]="backstage.io/kubernetes-id=argocd-instance"
    ["argocd-redis"]="backstage.io/kubernetes-id=argocd-instance"
    ["argocd-application-controller"]="backstage.io/kubernetes-id=argocd-instance"
    ["argocd-dex-server"]="backstage.io/kubernetes-id=argocd-instance"
    ["argocd-operator"]="backstage.io/kubernetes-id=argocd-operator"
    # Demo applications
    ["guestbook"]="backstage.io/kubernetes-id=argocd-demo"
  )

  resource_types=("pods" "deployments" "replicasets" "services" "routes" "statefulsets")

  for resource in "${resource_types[@]}"; do
    for pattern in "${!patterns[@]}"; do
      label="${patterns[$pattern]}"
      oc get "$resource" -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" 2>/dev/null \
        | grep "$pattern" \
        | xargs -I {} oc label "$resource" {} "$label" --overwrite -n $NAMESPACE 2>/dev/null || true
    done
  done
  
  echo "Labels applied successfully!"
}

register_argocd_demo_catalog_entities() {
  # Check if demo data population is enabled
  if [[ "${POPULATE_DEMO_DATA:-true}" == "false" ]]; then
    echo "Demo data disabled, skipping catalog entity registration..."
    return 0
  fi

  echo "Registering ArgoCD demo catalog entities..."

  # Create ConfigMap for demo catalog entities
  oc create configmap argocd-demo-entities-config-map \
    --from-file=demo-argocd-applications.yaml=$PWD/resources/argocd/demo-catalog-entities.yaml \
    --namespace=${NAMESPACE} \
    --dry-run=client -o yaml | oc apply -f - --namespace=${NAMESPACE}

  # Add label for Backstage to discover
  oc label configmap argocd-demo-entities-config-map \
    backstage.io/kubernetes-id=developer-hub \
    --overwrite -n ${NAMESPACE}

  echo "Demo catalog entities registered!"
  echo "Entities will be available in RHDH catalog:"
  echo "  - Component: demo-guestbook-app (RoadieHQ annotations)"
  echo "  - Component: demo-helm-app (Backstage Community annotations)"
  echo "  - Component: demo-kustomize-app (Both annotation styles)"
}

uninstall_argocd() {
  echo "Uninstalling ArgoCD..."

  # Delete demo catalog entities ConfigMap
  oc delete configmap argocd-demo-entities-config-map --namespace=${NAMESPACE} 2>/dev/null || true

  # Delete demo applications
  oc delete -f $PWD/resources/argocd/demo-applications.yaml --namespace=${NAMESPACE} 2>/dev/null || true

  # Delete ArgoCD instance
  oc delete argocd argocd --namespace=${NAMESPACE} 2>/dev/null || true

  # Wait for resources to be cleaned up
  sleep 10

  # Uninstall the operator
  OPERATOR=$(oc get csv --namespace=${NAMESPACE} 2>/dev/null | grep argocd-operator | awk '{print $1}')
  if [[ -n "$OPERATOR" ]]; then
    oc delete clusterserviceversion $OPERATOR --namespace=${NAMESPACE}
  fi
  oc delete subscription argocd-operator-subscription --namespace=${NAMESPACE} 2>/dev/null || true

  echo "ArgoCD uninstalled!"
}

main() {
  source "${PWD}/env_variables.sh"
  source "${PWD}/.env"

  echo "=============================================="
  echo "Configuring ArgoCD Plugin"
  echo "=============================================="

  deploy_argocd
  wait_for_argocd_operator_and_deploy_instance
  wait_for_argocd_instance_and_deploy_demo_applications
  config_secrets_for_argocd_plugins
  apply_argocd_labels
  register_argocd_demo_catalog_entities

  echo ""
  echo "=============================================="
  echo "ArgoCD configuration complete!"
  echo "=============================================="

  exit "${OVERALL_RESULT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
