apiVersion: image.openshift.io/v1
kind: ImageStreamImport
metadata:
  name: internal-minio
spec:
  import: true
  images:
    - from:
        kind: DockerImage
        name: quay.io/minio/minio:latest
      to:
        name: latest
      importPolicy:
        insecure: false # Set to true if using an insecure registry
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: internal-minio
spec:
  lookupPolicy:
    local: true # Ensure the image is resolved locally
