apiVersion: image.openshift.io/v1
kind: ImageStreamImport
metadata:
  name: internal-nginxdemos-hello
spec:
  import: true
  images:
    - from:
        kind: DockerImage
        name: nginxdemos/hello:plain-text
      to:
        name: plain-text
      importPolicy:
        insecure: false # Set to true if using an insecure registry
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: internal-nginxdemos-hello
spec:
  lookupPolicy:
    local: true # Ensure the image is resolved locally
