apiVersion: image.openshift.io/v1
kind: ImageStreamImport
metadata:
  name: internal-redis
spec:
  import: true
  images:
    - from:
        kind: DockerImage
        name: redis:6.2
      to:
        name: '6.2'
      importPolicy:
        insecure: false # Set to true if using an insecure registry
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: internal-redis
spec:
  lookupPolicy:
    local: true # Ensure the image is resolved locally
